version: '3.8'

services:
  timer-app:
    image: timer-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - timer_data:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  timer_data: